--User Tables (Albert)
drop table if exists Users cascade;
drop table if exists Orders cascade;
drop table if exists Purchases;
drop table if exists Sellers;

CREATE TABLE if not exists Users (
    user_id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    address VARCHAR NOT NULL,
    balance REAL DEFAULT 0 CHECK(balance >= 0) NOT NULL
);

CREATE TABLE if not exists Orders (
    order_id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL REFERENCES Users(user_id),
    total_price REAL NOT NULL CHECK(total_price >= 0),
    total_items INT NOT NULL CHECK(total_items > 0),
    time_stamp timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE if not exists Purchases (
    order_id INT NOT NULL REFERENCES Orders(order_id),
    pid INT NOT NULL REFERENCES Products(product_id),
    quantity INT NOT NULL CHECK(quantity >= 0),
    fulfillment_status VARCHAR not null check(fulfillment_status in ('ordered', 'shipped', 'delivered')) 
);

CREATE TABLE if not exists Sellers (
    user_id INT NOT NULL REFERENCES Users(user_id)
);
