-- Product Feedback (Aaric)
drop table if exists Review;
CREATE TABLE if not exists Review (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(user_id),
    pid INT NOT NULL REFERENCES Products(product_id),
    review_time timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    review_content VARCHAR(255) NOT NULL
);